## Numpy array and basics

In [1]:
pip install numpy 


[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

### Array properties

In [44]:
array = np.array([1, 2, 3, 4])
print(array)

print("Array Diamesion:", array.ndim)
print("Array Shape:", array.shape)
print("Array Size mean how many element are containing in array :", array.size)
print("Data type:", array.dtype)
print("Each Item or Element Size:", array.itemsize)
print("total size of Array:", array.nbytes)
print("Tanspose of Array:", array.T)



[1 2 3 4]
Array Diamesion: 1
Array Shape: (4,)
Array Size mean how many element are containing in array : 4
Data type: int64
Each Item or Element Size: 8
total size of Array: 32
Tanspose of Array: [1 2 3 4]


In [63]:
array = np.array([[3, 5, 5],
                  [9, 90, 5],[6, 0, 57]])
print (array)
print(array.ndim)
print(array.shape)
print(array.size)
print(array.itemsize)
print(array.nbytes)
print(array.T)
print(array.dtype)

[[ 3  5  5]
 [ 9 90  5]
 [ 6  0 57]]
2
(3, 3)
9
8
72
[[ 3  9  6]
 [ 5 90  0]
 [ 5  5 57]]
int64


In [64]:
#Transpose

array = np.array([[4, 6, 7],[8, 5, 7]])
print(array.T) 

[[4 8]
 [6 5]
 [7 7]]


## Numpy Array Creation

######   np.ones()

######   np.linspace()

### np.array()

In [68]:
arr_1d = np.array([1, 2, 4, 5, 8])

print("1D Array:",arr_1d)

1D Array: [1 2 4 5 8]


In [79]:
arr_2d = np.array([[3, 5, 5],
                   [8, 8, 8]])

print ("2D Aarray:\n" , arr_2d)

2D Aarray:
 [[3 5 5]
 [8 8 8]]


###  np.zeros()


In [93]:
zero_matrix = np.zeros((7, 7))

print(zero_matrix)
print (zero_matrix.shape)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
(7, 7)


In [91]:
zero = np.zeros((1, 1))


print (zero)
print (zero.shape)

[[0.]]
(1, 1)


### np.arange

In [82]:
array = np.arange(10)

print (array)

[0 1 2 3 4 5 6 7 8 9]


In [84]:
array = np.arange(0, 59 , 3)

print (array)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]
